version: '2'
services:
  api:
    build: ./node
    ports:
     - "8090:8090"
    depends_on:
      - redis
    links:
      - "redis:redis"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
